# Generated by Django 4.0.3 on 2022-03-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('average_age', models.FloatField()),
                ('district_code', models.IntegerField()),
                ('departement_code', models.CharField(max_length=20)),
                ('region_code', models.IntegerField()),
                ('region_name', models.CharField(max_length=200)),
            ],
        ),
    ]
